const data = {
  _id: {
    $oid: "68a1d556dc9882a22e6b1bef",
  },
  applicationId: "KYCAPP00041",
  entityName: "Ebitaus Private Limited",
  entityType: "PRIVATE_LIMITED",
  cin: "U62099TN2023PTC158659",
  llpin: "",
  pan: "AAHCE4484E",
  reason: "KYC Application",
  authorizedSignatories: [
    {
      ausId: "5892bb95-95cf-40f5-8892-dd821e3d8d62",
      fullName: "Nishanthan",
      title: "",
      emailAddress: "nishanthan.karunakaran@ebitaus.com",
      phoneNumber: "",
      isValidatedAtBR: false,
      personalDocuments: {
        proofOfIdentity: {
          data: {
            fileName: null,
            s3Url: null,
            extractedContent: {},
          },
          options: [
            {
              text: "Pan Card",
              value: "personalpan",
              key: "personalpan",
            },
            {
              text: "Aadhaar Card",
              value: "aadhaar-identity",
              key: "aadhaar-identity",
            },
            {
              text: "Driving Licence",
              value: "driving",
              key: "driving",
            },
            {
              text: "Passport",
              value: "passport",
              key: "passport",
            },
          ],
          selectedType: "personalpan",
          label: "Proof of Identity",
          type: "proofOfIdentity",
          acceptedTypes: "pdf, jpg, jpeg, png",
        },
        proofOfAddress: {
          data: {
            fileName: null,
            s3Url: null,
            extractedContent: {},
          },
          options: [
            {
              text: "Aadhaar Card",
              value: "aadhaar-address",
              key: "aadhaar-address",
            },
            {
              text: "Driving Licence",
              value: "driving",
              key: "driving",
            },
            {
              text: "Passport",
              value: "passport",
              key: "passport",
            },
            {
              text: "Electricity bill (Not more than 2 months)",
              value: "electricity",
              key: "electricity",
            },
            {
              text: "Internet bill (Not more than 2 months)",
              value: "internet",
              key: "internet",
            },
            {
              text: "Gas bill (Not more than 2 months)",
              value: "gas",
              key: "gas",
            },
            {
              text: "Landline bill (Not more than 2 months)",
              value: "landline",
              key: "landline",
            },
            {
              text: "Bank Statement",
              value: "bank",
              key: "bank",
            },
            {
              text: "Rental Agreement/Lease Agreement",
              value: "rental",
              key: "rental",
            },
            {
              text: "Property Tax Receipt",
              value: "property",
              key: "property",
            },
          ],
          selectedType: "aadhaar-address",
          label: "Proof of Address",
          type: "proofOfAddress",
          acceptedTypes: "pdf, jpg, jpeg, png",
        },
        photograph: {
          data: {
            fileName: null,
            s3Url: null,
            extractedContent: {},
          },
          label: "Upload Photograph",
          acceptedTypes: "jpg, jpeg, png",
          type: "photograph",
        },
        specimenSignature: {
          data: {
            fileName: null,
            s3Url: null,
            extractedContent: {},
          },
          label: "Upload Specimen Signature",
          type: "signature",
          acceptedTypes: "jpg, jpeg, png",
        },
      },
    },
  ],
  beneficialOwners: [
    {
      boId: "1aad7b39-2ced-4adc-b6ca-6b6807979c5d",
      name: "",
      addressLine: "",
      share: "",
      pan: "",
      pinCode: "",
    },
  ],
  boAnswers: [3],
  directors: [
    {
      dirId: "0cc59832-1331-4ed1-ba26-a19767f47fc6",
      fullName: "PITCHAI VENKATESH",
      din: "10061417",
      pan: "CIXPN9255M",
      aadhaar: "121212121212",
      dateOfAppointment: "03/03/2023",
      designation: "Director",
      dateOfBirth: "08/06/1978",
      personalDocuments: {
        proofOfIdentity: {
          documentSubType: "personalpan",
          fileName: "Nishanthan Pan Card.pdf",
          s3Url:
            "https://ebi-kycus.s3.amazonaws.com/kyc/KYCAPP00041/personaldocs/PITCHAI VENKATESH-0cc59832-1331-4ed1-ba26-a19767f47fc6/Nishanthan_Pan_Card.pdf",
          verificationData: {
            verifiedOn: "2025-08-17T19:02:38.707405",
            isVerified: true,
            validationType: "Internal",
            isPanDobMatched: true,
          },
          extractedData: {
            name: "Aman Kumar",
            "PAN Number": "CXKPK9255M",
          },
          selectedType: "personalpan",
          uploadedAt: "2025-08-17T19:02:34.283238",
        },
        proofOfAddress: {
          documentSubType: "aadhaar-address",
          fileName: "Nishanthan Aadhaar Card.pdf",
          s3Url:
            "https://ebi-kycus.s3.amazonaws.com/kyc/KYCAPP00041/personaldocs/PITCHAI VENKATESH-0cc59832-1331-4ed1-ba26-a19767f47fc6/Nishanthan_Aadhaar_Card.pdf",
          verificationData: {
            verifiedOn: "2025-08-17T19:03:18.749062",
            isVerified: true,
            validationType: "Internal",
            isAadhaarDobMatched: true,
          },
          extractedData: {
            name: "Nishanthan Karunakaran",
            address:
              "S/O: Karunakaran, 5/59, KOTTAI NAICKEN STREET, Kalappanayakkenpatti, PO: Kalappanaickenpatti, DIST: Namakkal, Tamil Nadu - 637404",
            fatherName: "Karunakaran",
          },
          selectedType: "aadhaar-address",
          uploadedAt: "2025-08-17T19:02:59.113560",
        },
      },
      isVerifiedByUser: true,
    },
    {
      dirId: "bb95f90b-14fd-44bc-a9ae-869eda9776b6",
      fullName: ". KOKILA",
      din: "10061418",
      pan: "",
      dateOfAppointment: "03/03/2023",
      designation: "Director",
      dateOfBirth: "04/07/1981",
      personalDocuments: {},
      isVerifiedByUser: false,
    },
  ],
  entityDocs: {
    pan: {
      fileName: "1. PAN - Ebitaus.pdf",
      s3Url:
        "https://ebi-kycus.s3.amazonaws.com/kyc/KYCAPP00041/entitydocs/documents/1.-PAN---Ebitaus.pdf",
      type: "pan",
      label: "PAN",
      isRequired: true,
      extractedContent: {
        companyName: "EBITAUS PRIVATE LIMITED",
        PAN: "AAHCE4484E",
      },
      uploadedAt: "2025-08-17T18:44:41.862486",
      verificationData: {
        verifiedOn: "2025-08-17T18:44:41.859233",
        isVerified: true,
        validationType: "PAN",
      },
    },
    certificate_of_incorporation: {
      fileName: "Certificate of Incorporation",
      type: "coi",
      label: "Certificate of Incorporation",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
    },
    gst_certificate: {
      fileName: "GST Certificate",
      type: "gst",
      label: "GST Certificate",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
    },
    memorandum_of_association: {
      fileName: "Memorandum of Association",
      type: "moa",
      label: "Memorandum of Association",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
    },
    articles_of_association: {
      fileName: "Articles of Association",
      type: "aoa",
      label: "Articles of Association",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
    },
    board_resolution: {
      fileName: "Board Resolution",
      type: "br",
      label: "Board Resolution",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
      verificationData: {
        verifiedOn: "2025-08-17T19:02:38.707405",
        isVerified: true,
        validationType: "Internal",
        result: {
          status: "success",
          message: "Document uploaded and processed successfully",
          data: {
            documentId: "bfba639c-7463-4d16-8dba-119f81c57113",
            processingStatus: "COMPLETED",
            fileInfo: {
              fileName: "BR_Kumar Signed (2).pdf",
              fileSize: 216492,
              contentType: "application/pdf",
              documentType: "PDF",
              uploadedAt: "2025-08-21T06:55:35.05652",
              uploadedBy: "nishanthan.karunakaran@ebituas.com",
              uploadedFromIp: "0:0:0:0:0:0:0:1",
              s3Url:
                "https://ebi-kycus.s3.ap-south-1.amazonaws.com/br-documents/bfba639c-7463-4d16-8dba-119f81c57113/BR_Kumar Signed (2).pdf",
              fileSizeFormatted: "211.4 KB",
            },
            entity: {
              companyName: "EBITAUS PRIVATE LIMITED",
              entityType: "PRIVATE_LIMITED",
            },
            directors: [
              {
                id: "b5a3aba1-6bc1-4eb4-9ec8-e83b5e36ebd2",
                fullName: "PITCHAI VENKATESH",
                din: "10061417",
                designation: "Director",
                appointmentDate: "2023-03-03",
                parentName: "",
                nationality: "Indian",
                isIndependent: false,
                isExecutive: false,
                isActive: true,
              },
              {
                id: "33de63d4-d928-4e02-9a8b-d959960076e9",
                fullName: ". KOKILA",
                din: "10061418",
                designation: "Director",
                appointmentDate: "2023-03-03",
                parentName: "",
                nationality: "Indian",
                isIndependent: false,
                isExecutive: false,
                isActive: true,
              },
            ],
            authorizedUsers: [
              {
                id: "fccc3a0f-6d85-40c0-be71-101e420cdcaf",
                fullName: "Kumar Nagaraj",
                isActive: true,
                isKeyManagerialPersonnel: false,
                authorizations: [
                  {
                    authorizationType: "Banking Operations",
                    description:
                      "Operating bank accounts, making banking transactions, submitting required documents, and performing other necessary activities related to the Company’s banking operations.",
                    currency: "INR",
                    specificConditions: [],
                    requiresBoardApproval: false,
                    requiresCoSignature: false,
                    coSignatories: [],
                    isActive: true,
                  },
                ],
                individualKYC: {
                  status: "NOT_STARTED",
                },
              },
            ],
            meetingInfo: {
              meetingDate: "2025-08-04T00:00:00",
              meetingVenue: "Registered Office of the Company",
            },
            processingInfo: {
              processingDurationMs: 55564,
              aiModel: "gpt-4o-mini",
              extractionConfidence: 0.825,
              extractionAttempts: 1,
              lastProcessedAt: "2025-08-21T06:56:30.614174",
              extractionEngineVersion: "1.0.0",
            },
            documentMetadata: {
              language: "en",
              documentFormat: "auto-detected",
              wasPasswordProtected: false,
              containsImages: false,
              containsTables: true,
              textQualityScore: 0.825,
            },
            additionalNotes: "Purpose: Appointment of Authorised Signatory",
            reviewInfo: {
              isManuallyReviewed: false,
              isArchived: false,
            },
            signatureDetails: {
              isDigitallySigned: true,
              signatureStatus: "VALID",
              signerDetails: {
                signerName: "PITCHAI VENKATESH",
                signerOrganization: "EBITAUS PRIVATE LIMITED",
                signerCountry: "IN",
                signedAt: "2025-08-04T18:47:55",
                signingReason: "",
                signingLocation: "",
              },
              certificateDetails: {
                certificateClass: "Class 3",
                issuerName: "SignX sub-CA for Class 3 Organization 2022",
                serialNumber: "134574839572175",
                validFrom: "2024-02-19T17:59:08",
                validUntil: "2026-02-19T17:59:08",
                keyUsage: "Digital Signature, Non-repudiation",
                signatureAlgorithm: "SHA256withRSA",
                isEmudhraIssued: false,
              },
              documentIntegrity: {
                isDocumentTampered: false,
                isSignatureIntact: true,
                integrityStatus: "INTACT",
                lastModifiedInfo: "Signature verification completed",
              },
              validationTimestamp: "2025-08-21T06:55:39",
              validationNotes: "Signing reason: .",
            },
            brInfo: {
              brDate: "2025-08-04",
              purpose: "Appointment of Authorised Signatory",
              meetingVenue: "Registered Office of the Company",
              entityName: "Ebitaus Private Limited",
              signedBy: "Venkatesh",
              signingDate: "2025-08-04",
            },
            authorizedPersons: {
              authorizedPersons: [
                {
                  fullName: "Kumar Nagaraj",
                  role: "Director/Employee",
                  authorizations: [
                    {
                      authorizationType: "Banking Operations",
                      description:
                        "Operating bank accounts, making banking transactions, submitting required documents, and performing other necessary activities related to the Company’s banking operations.",
                      currency: "INR",
                      specificConditions: [],
                      requiresBoardApproval: false,
                      requiresCoSignature: false,
                    },
                  ],
                },
              ],
            },
            createdAt: "2025-08-21T06:55:35.056931",
            updatedAt: "2025-08-21T06:56:30.61431",
          },
        },
      },
    },
    address_proof: {
      fileName: "Address Proof",
      type: "address_proof",
      label: "Address Proof",
      acceptedTypes: "pdf, jpg, jpeg, png",
      isRequired: true,
      extractedContent: {},
      selectedType: "electricity",
      options: [
        {
          text: "Electricity Bill (Not more than 2 months)",
          value: "electricity",
          key: "electricity",
        },
        {
          text: "Internet Bill (Not more than 2 months)",
          value: "internet",
          key: "internet",
        },
        {
          text: "Landline Bill (Not more than 2 months)",
          value: "landline",
          key: "landline",
        },
        {
          text: "Bank Statement",
          value: "bank_statement",
          key: "bank_statement",
        },
        {
          text: "Rental Agreement/Lease Agreement",
          value: "rental_agreement",
          key: "rental_agreement",
        },
        {
          text: "Property Tax Receipt",
          value: "property_tax",
          key: "property_tax",
        },
      ],
    },
  },
  mailingAddress: {},
  registeredAddress: {},
  stepper: [
    {
      key: 0,
      label: "Welcome",
      isCompleted: true,
    },
    {
      key: 1,
      label: "Entity Details",
      isCompleted: true,
    },
    {
      key: 2,
      label: "Personal Details",
      isCompleted: false,
    },
    {
      key: 3,
      label: "KYC Form",
      isCompleted: false,
    },
    {
      key: 4,
      label: "eSign & Status",
      isCompleted: false,
    },
  ],
  currentStep: 2,
  isEsignInitiated: false,
  isVkycInitiated: false,
  submittedByBankerId: "6860c95670dd7b6bfbe4693d",
  submittedByBankerName: "Nishanthan Karunakaran",
  submittedByBankerEmail: "nishanthan.karunakaran@ebitaus.com",
  submittedAt: {
    $date: "2025-08-17T13:12:54.489Z",
  },
  updatedAt: {
    $date: "2025-08-17T13:17:54.229Z",
  },
  isSigningCompleted: false,
  status: "IN_PROGRESS",
  kycFormStatus: "In Progress",
  annexure1: {
    values: {
      globalEntityIdentificationNo: false,
      other: false,
      tin: false,
      cin: true,
    },
  },
  _class: "com.ebitaus.kycus.features.banker.kyc.entity.KycApplication",
};